version: "3"
services:
  code-verify:
    build: .
    volumes:
      - ./app:/app/app
      - ./tools:/app/tools
    ports:
      - "3002:3002"
    networks:
      - backend
    depends_on:
      - mongo
  mongo:
    image: mongo
    networks:
      - backend
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"

networks:
  backend:
    driver: bridge